### ISSUE TITLE
Aggiornare glossario

### ISSUE THREAD

**Issue by mikigatto93** [DreamTeamSWE/Documenti#110]
Aggiungere termini: 
- [x] Serverless
- [x] api gateway
- [x] eventbridge
- [x] sqs
- [x] react
- [x] cognito
- [x] amplify
- [ ] media
- [x] location
- [x] label

**Comment by imGretaas** [comment]
Documento verificato da Luciano in data 13/05/22

**Comment by imGretaas** [comment]
Termini approvati:

- [x] Serverless
- [x] api gateway
- [x] eventbridge
- [x] sqs
- [x] react
- [x] cognito
- [x] amplify
- [ ] media
- [x] location
- [x] label

**Comment by imGretaas** [comment]
@mikigatto93 non trovo media...

**Comment by imGretaas** [comment]
per il resto tutto ok

**Comment by imGretaas** [comment]
ok, trovato anche media! tutto bene
