### ISSUE TITLE
AdR sistemati i requisiti

### ISSUE THREAD

**Issue by imGretaas** [DreamTeamSWE/Documenti#111]
Ciao raga, dareste un'occhiata all'AdR? Sono stati aggiornati i requisiti (aggiunti dei requisiti funzionali, in accordo con i nuovi casi d'uso creati, e sistemato l'ultimo capitolo)

[Link alla versione aggiornata](https://github.com/DreamTeamSWE/Documenti/blob/AdR/AnalisiDeiRequisiti/AnalisiDeiRequisiti.pdf)

**Comment by Pitora** [comment]
Pagina 41 : R1FW11.2.3 : Errore nella descrizione
Pagina 41 : R2FW12 ripetuto due volte

**Comment by imGretaas** [comment]
Fatto, grazie
