### ISSUE TITLE
Manuale Utente

### ISSUE THREAD

**Issue by imGretaas** [DreamTeamSWE/Documenti#120]
Prima versione manuale da verificare: [link](https://github.com/DreamTeamSWE/Documenti/tree/ManualeUtente/ManualeUtente)

**Comment by Pitora** [comment]
Mi sembra vadi bene. Le cose che non mi convincono sono : 

- "5 Login" : Sebbene si parli del login, nella parte iniziale si parla di come si possa accedere all'area personale più e più volte. Piuttosto parlerei solo del login e dopo, nella sezione "7 Area Personale" parlerei di come accedere ad essa.
- Funzionalità non ancora implementata : Sono d'accordo sul metterlo dove serve e anche a ripeterlo tra paragrafi diversi nonostante si stia parlando della stessa funzionalità. Però cerca di non esagerare. Per esempio in 9.1 non serve che lo metti nell'elenco sull'icona a cuore e dopo spiegarlo di nuovo a fine paragrafo. In questo caso lascerei la spiegazione a fine paragrafo e toglierei le altre due. Inoltre cerca di mantenere la dicitura coerente : per esempio nel paragrafo 7.4 se metti tra parentesi (funzionalità ...)una volta, mettila anche la seconda.

**Comment by imGretaas** [comment]
Sistemato tutto, grazie mille @Pitora !

**Comment by mikigatto93** [comment]
- [x] Glossario v1.0.0 sull introduzione va messo v2.0.0
- [ ] Punti e virgola sulle liste (da norme, vedi te poi se hai tempo)
- [x] Sloggarsi come termine non é il massimo, metti tipo disconnettersi
- [x] Sez 8 boh mi pare ridondante sempre mettere il sito web, e vedete se riuscite a non fare andare a capo la parentesi

Per il resto ok

**Comment by imGretaas** [comment]
Ok, grazie Mik!
