### ISSUE TITLE
Piano di Progetto

### ISSUE THREAD

**Issue by imGretaas** [DreamTeamSWE/Documenti#121]
[Link al documento](https://github.com/DreamTeamSWE/Documenti/tree/PianodiProgetto)

**Comment by imGretaas** [comment]
Documento verificato, ci sono alcune cose da correggere (trovate i commenti nel documento in allegato) @Baxxo @httpedo13 

[piano_di_progetto.pdf](https://github.com/DreamTeamSWE/Documenti/files/8771092/piano_di_progetto.pdf)

Attenzione a mettere Manuale delle API o, meglio ancora, Documentazione API, anziché manuale dello sviluppatore

**Comment by imGretaas** [comment]
Da rimuovere il commento a pagina 12: DA ELIMINARE? secondo me no, ho aggiunto nell'occorrenza dei rischi come abbiamo sistemato (MB)

e le cornici attorno ai link: \usepackage[hidelinks]{hyperref} (da inserire nel file packages.tex)

**Comment by Baxxo** [comment]
rimangono da sistemare

- [ ] diagrammi da aggiungere
- [ ] 4.3.6.4
- [ ] 4.3.8.4
- [ ] 4.4
- [ ] 4.4.2.3

**Comment by edoardop13** [comment]
- [x] tolto il commento a pag12
- [x] sistemati i link rossi
- [x] corretto "documentazione API"
- [x] sistemati gli errori individuati da @imGretaas 

Manca:
- [ ] inserire i gantt
- [ ] rileggere le conclusioni dei consuntivi
- [ ] aggiungere un preventivo finale alla fine della sezione "preventivo"
- [ ] sistemare registro modifiche
