### ISSUE TITLE
Da sistemare nel Piano di Progetto

### ISSUE THREAD

**Issue by francescoo22** [DreamTeamSWE/Documenti#28]
- [x] nel registro delle modifiche il ruolo che svolge chi fa il piano di progetto è amministratore/responsabile
- [x] 2.1 - Problemi hardware, non c'è la parte di conseguenze
- [x] paragrafi 2.2, 2.3, 2.4 non sono separati
- [x] non c'è la parte di conseguenze nel calcolo dei costi

**Comment by Baxxo** [comment]
- cambiato ruolo nel registro modifiche (da analista a responsabile)
- aggiunte conseguenze alla sezione 2.1
-  **Manca da capire perché non sono separate, almeno da editor di github sembrano separate (forse basta ricompilare)**
- aggiunta conseguenza al calcolo dei costi

**Comment by francescoo22** [comment]
ho compilato il pdf e sistemato una tabella, i paragrafi 2.2, 2.3, 2.4 non si sono sistemati.
Poi vedendo i documenti dei gruppi degli anni scorsi ho visto che non mettono sempre responsabile come ruolo, ma anche amministratore (onestamente non so in base a cosa)

**Comment by Baxxo** [comment]
@francescoo22  da verificare ultime modifiche ed eventualmente chiudere

**Comment by francescoo22** [comment]
resta solo da sistemare il registro delle modifiche che deve rispettare quanto scritto nelle norme di progetto:

- [x] le date in formato YYYY-MM-DD
- [x] il verificatore deve essere riportato ad ogni modifica
Poi non sono così sicuro che il ruolo sia sempre responsabile perché vedendo altri progetti noto che mettono anche amministratore

**Comment by Baxxo** [comment]
- [ ] ho un dubbio se ho fatto corretto il versionamento nella tabella nel registro delle modifiche
- [ ] la data di fine stesura del Glossario dovrebbe essere uguale a quella del rilascio (?)
