### ISSUE TITLE
Verifica documentazione

### ISSUE THREAD

**Issue by mikigatto93** [DreamTeamSWE/Documenti#32]
Verifica di #31

**Comment by francescoo22** [comment]
NormeDiProgetto/Contenuto/Sezioni/ProcessiSupporto.tex 
- [x] 4 - scriverei Ogni processo e attività per lo sviluppo del progetto dovrà essere documentato, o qualcosa di diverso comunque perchè per come è ora mi suona male
- [x] 19 - "il consuntivi di periodo" penso sia "i consuntivi di periodo." , poi alla fine ci va il ";"
- [x] 198 - mi sembra che Tullio ha detto che è meglio il formato anno/mese/giorno perchè ordinabile in modo lessicografico, comunque vedete voi cosa è meglio

**Comment by edoardop13** [comment]
NormeDiProgetto/Contenuto/Sezioni/ProcessiSupporto.tex

- [x] 7 - spazio prima dei due punti
- [x] 18 - correggerei con "dove sono presenti i termini tecnici usati nella documentazione" e toglierei "se il gruppo lo ritene necessario"
- [x] 20 - toglierei "espone"
- [x] 21 - correggerei "che presenta" con "contenente" 
- [x] 96 - toglierei "finale"
- [x] 97 - ripeti due volte "scopo" 
- [x] in generale nella sezione 3.1.6 troppi "contiene"
- [x] sezione 3.1.7.1 troppi "indica"
- [x] 139 - lascerei una delle due parole, o "orientarsi" o "individuare"
- [x] 145 - manca la lettera maiuscola
- [x] sezione 3.1.7.4 lo spiegherei più semplicemente come intestazione, contenuto e piè di pagina o header, body e footer
- [x] 184 - metti delle virgole o togli "da enfatizzare"
- [x] 185 - "dei documenti o dei paragrafi" forse suona meglio
- [x] 3.1.8.4 controlla perchè ci sono alcuni elenchi che non iniziano con una lettera maiuscola
- [x] 237 - spazio prima dei ":"
- [x] 3.1.8.7 - spazio prima dei ":" da togliere
