### ISSUE TITLE
Analisi dei requisiti

### ISSUE THREAD

**Issue by francescoo22** [DreamTeamSWE/Documenti#33]
- [x] sistemare l'indice
- [ ] sistemare termini glossario
- [ ] uniformare schemi UML
- [x] aggiornare registro modifiche

**Comment by imGretaas** [comment]
- [ ] ultimare requisiti funzionali
- [ ] ultimare requisiti di qualità
- [ ] ultimare requisiti di vincolo

**Comment by francescoo22** [comment]
c'é un piccolo errore nell'UML del UC2->UC2.3 dove c'é scritto "modificare l'indirizzo lo username/email"

**Comment by imGretaas** [comment]
Dopo l'incontro in data 11.01.22 delle 12:30 con Cardin, per gli Schemi UML dobbiamo sistemare:

- [x] Rimuovere social generico
- [x] Aggiungere casi d'uso versione mobile
- [ ] Aggiungere casi d'uso versione webapp
- [x] Aggiungere casi d'uso per gli errori

Nel file latex:
- [ ] Aggiungere descrizione per ogni caso d'uso
- [ ] Aggiungere la caption sotto ogni immagine

**Greta**
- [x] Sistemare Registrazione (con sottocasi)
- [x] Sistemare label 
- [x] Sistemare errori
- [x] Aggiungere UC2 - Area personale senza nient'altro 
- [x] Cambiare label sottocasi UC2 con “Area Personale” 
- [ ] Aggiungere label UC 2 - WebApp, Mobile App
- [ ] Togliere validità e salva in UC2.1/2.2 e attori secondari + inclusione = fare extend nei sottocasi di UC2 (2.1/2.2) per TT e IG. Collegare IG/TT al sottocaso di UC2
- [ ]  Via UC2.3.2 e analogo per la psw

**Francesco** 
- [ ] Va tolta tutta la parte dei social (attori secondari) ed il primo include (con tutta la parte di validità - 3.1 e 3.2)
- [ ] Va rimossa la generalizzazione nella gestione dei risultati. Vanno usati i sottocasi nei filtri di UC5
- [ ] Stesso discorso per UC6

**Luciano**
- [x] Da sistemare la generalizzazione di UC9 (crea UC9 per l'aggiunta del locale nella lista dei preferiti e UC10 per la rimozione del locale)

**Comment by imGretaas** [comment]
> c'é un piccolo errore nell'UML del UC2->UC2.3 dove c'é scritto "modificare l'indirizzo lo username/email"

Ok, risolto! Grazie mille

**Comment by imGretaas** [comment]
- [ ] Da sistemare la descrizione Generale
