### ISSUE TITLE
Piano di Qualifica

### ISSUE THREAD

**Issue by imGretaas** [DreamTeamSWE/Documenti#34]
Sistemare nel PdQ:

- [x] metriche di Prodotto (Luciano)
- [x] metriche di Processo (Francesco)
- [x] Obiettivi di qualità di processo
- [x] Obiettivi di qualità di prodotto
- [x] Sistemare le modifiche espresse in verifica ([verifica fatta da Michele](https://github.com/httpedo13/dreamteam_swe/pull/18))
- [x] descrizione standard SPICE
- [x] capire se percentuale requisiti soddisfatti è vincolo di prodotto o processo, perchè per ora è in entrambi

**Comment by Baxxo** [comment]
Ho notato che tra i verificatori c'è il mio nome, ma nel registro delle modifiche è riportato invece il nome di Michele

**Comment by francescoo22** [comment]
- [x] sistemare nomi verificatori
- [x] uniformare il registro delle modifiche

**Comment by imGretaas** [comment]
Manca la “Data di Approvazione” nella intro e la “v” davanti ad ogni numero di versione nel registro delle modifiche

**Comment by francescoo22** [comment]
tutto ok
