### ISSUE TITLE
Norme di progetto

### ISSUE THREAD

**Issue by Baxxo** [DreamTeamSWE/Documenti#35]
Nel registro delle modifiche nella stessa riga è riportato il ruolo di Amministratore e verificatore, penso debbano stare in 2 righe separate

**Comment by Baxxo** [comment]
- [ ] scopo del prodotto dovrebbe essere uniformato in tutti i documenti
- [ ] nell'elenco in 2.1.3 metterei i due punti tra testo in grassetto e descrizione
- [ ]  in 2.2.2, 2.2.4, 2.2.6, 2.2.8, 2.2.9 togliere lo spazio tra ultima parola e :
- [ ] in 2.2.4 nell'ultimo punto dell'elenco c'è la i maiuscola
- [ ] in 2.2.6 manca lo spazio tra 1.0.0 e presenta
- Arrivato fino a pagina 8

**Comment by imGretaas** [comment]
Da aggiornare il documento PDF delle norme

- [ ] Aggiornare PDF

**Comment by imGretaas** [comment]
Manca la data di approvazione del documento e la “v” prima di ogni numero di versione nel Registro delle Modifiche
