### ISSUE TITLE
Verifica Verbali

### ISSUE THREAD

**Issue by Pitora** [DreamTeamSWE/Documenti#37]
#36   #29 
- [x] Verifica Verbale Interno 13 Dicembre 2021
- [x] Verifica Verbale Interno 20 Dicembre 2021
- [x] Verifica Verbale Interno 29 Dicembre 2021
- [x] Verifica Verbale Interno 3 Gennaio 2022

- [x] Verifica Verbale Esterno 22 Dicembre 2022

**Comment by francescoo22** [comment]
Da sistemare:

- [x] I nomi di TUTTI i file pdf, tex e delle cartelle devono rispettare le NdP (Verbale[Tipologia]-[YYYY].[MM].[DD]
- [x] nel registro delle modifiche, nel riepilogo delle decisioni e nella data della riunione c'é da sistemare il formato delle date in YYYY-MM-DD
- [x] aggiungere nome del verificatore nel registro delle modifiche
- [x] Nel verbale esterno paragrafo 3.1 manca una parola

**Comment by imGretaas** [comment]
Da aggiungere “Data di approvazione” nella intro

**Comment by imGretaas** [comment]
il nome del verificatore va in corsivo e non in grassetto, secondo quanto scritto nelle norme
