### ISSUE TITLE
Verbale Interno 7 Gennaio 2021 - Ore 9

### ISSUE THREAD

**Issue by imGretaas** [DreamTeamSWE/Documenti#42]
- [x] Verbale Interno 7 Gennaio 2021

**Comment by francescoo22** [comment]
stessa cosa che avevo scritto negli altri verbali ovvero che c'é da sistemare le date nel formato scritto nelle NdP (YYYY-MM-DD)
del resto mi sembra tutto apposto

**Comment by imGretaas** [comment]
manca la “v” di versione, davanti alla versione - nel Registro delle Modifiche

**Comment by imGretaas** [comment]
Ok, fatto
