### ISSUE TITLE
Norme di Progetto

### ISSUE THREAD

**Issue by imGretaas** [DreamTeamSWE/Documenti#53]
Ciao, ho verificato il documento **NdP**. Il documento in sé va bene, secondo me, ma ci sono alcune cose da correggere che segnalo di seguito:

- [x] Rimuovere il mio nome come Analista nel registro delle modifiche..
- [x] Sistemare la “v” di versione prima del numero di versione nei documenti/registro modifiche. Attenzione che la v non va messa nell'Intro
- [x] Pagina 5 - da aggiungere uno spazio dopo la versione del glossario §1.3
- [x] Pagina 6 - Descrizione, manca un “del” prima di “prodotto finale” §2.1.2
- [x] Pagina 6 - da aggiungere uno spazio prima di “le finalità” nella documentazione fornita §2.1.3
- [x] Pagina 6 - strumenti §2.1.4, va indicato anche il software utilizzato per la creazione degli Schemi UML? In caso, abbiamo usato Diagrams.net o Draw.io (e non StarUML). Va inserito anche TexMaker? vedi §3.1.8.7
- [x] Pagina 7 - da aggiungere uno spazio dopo la versione dell’AdR in struttura §2.2.6
- [x] Pagina 7 - Struttura dell’AdR §2.2.6. L’AdR è stato aggiornato - ma non ancora verificato. Al suo interno, oltre a quanto già segnalato, si possono trovare anche: Casi d’uso e Requisiti
- [x] Pagina 7 - Da sistemare la tabellina §2.2.7 - Numero riferimento (RXF1) e Fonti (UC1)
- [x] Pagina 8 - **Da sistemare la classificazione casi d’uso (Abbiamo aggiunto anche i casi d’uso degli errori, delle webapp e mobile app.. perciò va inserito un nuovo identificativo del tipo E, W ed M prima del CodiceCasoBase**) 
- [x] Pagina 8 -  § 2.2.9 siamo sicuri che la qualità dei requisiti vada messa lì e non sotto al paragrafo relativo alla classificazione dei requisiti? Perché interessa più i requisiti che i casi d’uso
- [x] Pagina 11 - §3.1.6 (Struttura directory e file) in NomeDocumento.tex sistemare “tutti” con “tutte”
- [x] Pagina 11 - §3.1.6 (Struttura directory e file) in NomeDocumento.pdf sistemare “il” con “in”
- [x] Pagina 12 - §3.1.7.1 (Prima pagina) in “Uso” al posto di dire “dedicato” io metterei “destinato”
- [x] Pagina 12 - §3.1.7.2 (Registro delle Modifiche) l’ultimo punto riguarda il verificatore del documento, non so se lo includerei nel punto precedente (ossia la descrizione).. dato che abbiamo attuato questa convenzione
- [x] Pagina 12 - §3.1.7.4 (Struttura delle pagine) secondo punto “in” va cambiato con “In“ (I maiuscola)
- [x] Pagina 13 - §3.1.8.1 Nome dei documenti, attenzione al “TODO” presente nell’elenco puntato (v[X].[Y].[Z])
- [x] Pagina 13 - §3.1.8.1 Nome dei documenti, attenzione al formato della data.. ci va: YYYY-MM-DD, da sistemare anche nell’elenco puntato sottostante
- [x] Pagina 13 - §3.1.8.1 Stile di testo, nella descrizione di “Corsivo” togliere la e tra committenti e proponente, sostituire la congiunzione con la virgola
- [x] Pagina 13 - §3.1.8.4 Elementi testuali, in formati di data, cambiare il formato.. ci va: YYYY-MM-DD con il trattino
- [x] Pagina 14 - §3.1.8.5 Elementi grafici, i Diagrammi UML sono già stati inseriti nel documento e sì, sono presenti sotto forma di immagine in formato png
- [x] Pagina 15 - §3.2.4 Struttura del repo, attenzione al TODO 
- [x] Pagina 16 - §3.4.2 Descrizione, “La verifica viene APPLICATA”, anziché “applicato”
- [x] Pagina 16 - §3.4.3 Verifica della documentazione, io metterei in grassetto “Walkthrough” e “Inspection” come per il paragrafo precedente
- [x] Pagina 16 - §3.4.6 Test, In “Test d’unità” togliere il “sia” dopo il “Servono” nella prima riga
- [x] Pagina 16 - §4.1.2.1 Comunicazione, primo paragrafo, prima riga.. dopo il primo “tra i membri del team (interno)” ci va una virgola, anziché la “e”
- [x] Pagina 16 - Comunicazione interna, il mezzo di comunicazione non sarà Slack e telegram.. sono slack e telegram :D. Quando descrivi Slack, io metterei che il canale è già stato creato.. non che verrà creato. Idem per la parte di “Discord” nella parte inferiore del punto “Comunicazione interna”
- [x] Pagina 19 - §4.1.2.2 Riunioni interne, “Alle riunioni” anziché “alle riunione”. Aggiungere virgola prima del “ma” nell’ultima riga del paragrafo “Riunioni interne”
- [x] Pagina 19 - §4.1.2.2 Riunioni esterne, per quanto riguarda le riunioni esterne io metterei proponente e/o committente, anziché solo la ”e”, altrimenti sembra che per una riunione esterna sia necessario che ci siano entrambe le parti
- [x] Pagina 19 - §4.1.3 Pianificazione.. attenzione, quel paragrafo è da finire?
- [x] Pagina 19 - Ruoli di progetto, nel paragrafino esplicativo, togliere la virgola prima della “e”
- [x] Pagina 20 - Responsabile di progetto, via la “e” prima di “e di guidare”, da mettere una virgola
- [x] Pagina 21 - Gestione dei ticket, attenzione a //ciclo di vita del ticket// forse è da togliere o manca qualcosa?
- [x] Pagina 21 - Formazione interna, elenco puntato da completare

Non vogliatemi male, ve prego! :D 
Buon lavoro, Greta

**Comment by imGretaas** [comment]
Da tenere sotto controllo le versioni dei documenti, citati a pagina 6 nel §2.1.3.  §2.3.3 (AdR in Qualità), §2.4.2 (Piano di qualifica in descrizione)
Verificare i termini del glossario ed in caso aggiungere le G 
Vedo se riesco ad aggiungere una immagine in background per la prima pagina.. in caso, da aggiungere a §3.1.7.1
§3.2.4 Attenzione, dobbiamo attenerci a quanto scritto qui per il repo

Da cambiare il background delle righe da !10 a !25

**Comment by imGretaas** [comment]
Da aggiungere:

- [x] Nel registro di modifiche: quando si indica un solo paragrafo viene usato il simbolo § (ad esempio, §3.x), mentre, nel caso si indichino più paragrafi (dall'inizio alla fine), viene usato il doppio simbolo §§ (ad esempio, §§3.14-3.20)

**Comment by imGretaas** [comment]
- [x] Classificazione dei requisiti §2.2.7 - nelle “Fonti” va aggiunto anche “Decisione Interna” (dopo Capitolato d'appalto)

**Comment by imGretaas** [comment]
Attenzione! Nel registro delle modifiche compaiono due “Inizio stesura par 3”.. da sistemare questa cosa

**Comment by francescoo22** [comment]
fatto
