### ISSUE TITLE
Avvisi importanti modifiche su tutti i file latex

### ISSUE THREAD

**Issue by imGretaas** [DreamTeamSWE/Documenti#58]
Avvisi importanti sulle modifiche da apportare nei file latex 

- [ ] La tabella relativa al registro delle modifiche di ogni file va aggiornata. Al posto di table e tabular, ci va una longtable (questo perché, tra un po', le tabelle saranno molto lunghe e non ci staranno più in una pagina. Per mantenerle in un formato decente - evitando che debordino sul fondo e mantengano la posizione nel documento -, va cambiata la tipologia di tabella),
- [ ] Tutte le tabelle hanno righe alternate, una bianca ed una con sfonto \rowcolor{gray!25} (anziché !10). La prima riga dovrebbe essere su sfondo bianco - aggiungere il comando: `\rowcolors{2}{gray!25}{white}` prima del begin{table/tabular/longtable} e, nel caso ci sia una caption all'interno della tabella, va aggiunto `\hiderowcolors` prima della caption (in questo modo, si evita che la caption abbia sfondo grigio)
- [x] Di interesse per le NdP: Sono stati cambiati i casi d'uso, abbiamo adottato le diciture: UCW per la versione web e UCE per gli errori (niente UCM come previsto, in quanto non è richiesta la mobileapp grazie a Dio!)
- [ ] Ogni tabella deve avere una caption e nei file con le tabelle inseriamo anche l'indice delle tabelle (`\listoftables`)
- [ ] Ogni figura deve avere una caption e nei file con le figure inseriamo anche l'indice delle figure (`\listoffigures`)
- [ ] Va cambiato lo scopo del prodotto in tutti i documenti togliendo la parte della mobile app

**Comment by imGretaas** [comment]
Vanno aggiunti i termini del glossario ad ogni documento

**Comment by francescoo22** [comment]
fatto
