### ISSUE TITLE
Analisi dei Requisiti 

### ISSUE THREAD

**Issue by francescoo22** [DreamTeamSWE/Documenti#60]

**Comment by Pitora** [comment]
La verifica si concentra solo sulla parte 3 (come indicato dalla issue).

- [x] Paragrafo 3.5.1 : Mancano dei punti/punti e virgola alla fine delle frasi.
- [x] Paragrafo 3.5.3 : Mancano dei punti/punti e virgola alla fine delle frasi.
- [x] Paragrafo 3.10 : Scenario Principale : "L'utente cicca" da correggere.
- [x] Paragrafo 3.11 : Estensioni : Ripetizione di utente.
- [x] Paragrafo 3.23 : Titolo : "Visualizzza" da correggere.
- [x] Paragrafo 3.29 : Titolo : "Visualizzza" da correggere.
I riferimenti agli altri paragrafi mi sembrano giusti, ma un altro controllo non guasterebbe.

**Comment by imGretaas** [comment]
Grazie @Pitora per la dettagliata correzione!

**Comment by mikigatto93** [comment]
CAPITOLO 4:
- requisiti di vincolo:
  

- [x] R1V7: Metterei "...il servizio di calcolo AWS Lambda"
- [x] R2V2: anche qua come sopra "il servizio AWS API Gateway"
- R2V4: Non so ancora se serva Node.js, poi vedremo
- R1V6: Mi SEMBRA ridondante, però lo lascerei
- [x] A sto punto metterei anche che usiamo aws recognition e compagnia bella

- Requisiti di qualità

- [x] mi pare tutto ok, magari specificare che la documentazione è in italiano 
- [x] aggiungerei un altro requisito per il fatto che il codice sorgente sarà messo su github. 
- [x] Vedo da altri che mettono il manuale, effettivamente mi sembrava dovessimo presentarne uno

-Requisiti funzionali
 - R1FW8 che è generico lo mettiamo obbligatorio, però tutte le opzioni di filtro sotto sono desiderabili, io metterai almeno quella per punteggio obbligatoria, nel senso che se vanno filtrati, ci deve per forza essere qualche opzione di filtro che poi mettiamo obbligatoria.
 
poi metterei tutta la roba relativa a login e registrazione obbligatoria (mostrare errori/notifiche al login se qualcosa non va,  recupero password ed errori relativi e la possibilità di collegare i profili tiktok e insta).

Poi non manca qualcosa relativa a come facciamo lavorare i crawler e come componiamo le classifiche (cioè come facciamo l'analisi dei dati e distribuiamo i punteggi) ?

ultima cosa (la sapete già sicuramente, la scrivo per completezza) requisiti prestazionali è incompleto, non so se sia pertinente ma metterei, ad esempio, il discorso di salvare hash delle immagini per evitare di fare due volte l'analisi della stessa immagine.

**Comment by Pitora** [comment]
Verifica complessiva documento : 
nella seconda parte sono presenti dei riferimenti al glossario ridondanti per certi termini : ranking, piattaforma, crawling etc Questo problema di ridondanza è presente solo nella seconda parte. Per il resto, tutto bene. Si può far approvare il documento dopo la correzione.

**Comment by imGretaas** [comment]
Ok, fatto! Aggiunto anche dei termini negli strumenti! Da approvare

**Comment by edoardop13** [comment]
Capitolo 2:

- [ ] 2.2.2 nell'elenco puntato alla prima voce c'è una G di troppo;

**Comment by Baxxo** [comment]
[] Utilizzare account Instagram diversi da cui effettuare il crawling;
[] 2 punto di tiktok, porta al ban di (e manca di cosa)
[] 4 punto tiktok viene ripetuto necessaria, secondo me si può togliere il primo

**Comment by edoardop13** [comment]
Sezione 3.6
nell'elenco puntato delle estensioni non dovrebbe essere "nel caso in cui l'utente inserisca"?

**Comment by francescoo22** [comment]
sistemato

**Comment by edoardop13** [comment]
Sezione 5.2

- [ ] al primo elenco puntato la I di "instagram" è minuscola;
- [ ] nel secondo punto manca la parola account;
- [ ] nel punto 6 e 7 tiktok con la t minuscola;
- [ ] google maps in maiuscolo;

**Comment by imGretaas** [comment]
Modifiche da apportare dopo il semaforo verde di Cardin:

- [ ] Registro delle modifiche (da modificare la riga della verifica di coesione e coerenza complessiva)
- [x] UCW4: “Area Personale” non è una funzionalità. I casi d’uso modellano funzionalità del sistema, non sue componenti. 
- [x] UCW7 è appena abbozzato. Quali informazioni sono disponibili nella classifica? 
- [x] Idem per UCW11.

Di conseguenza, vanno aggiornati requisiti e tracciamento!

**Comment by Pitora** [comment]
Premetto che questa non è una verifica di coesione. Sono stati controllati i casi UCW4, UCW7 e UCW11. 
Tutto in ordine. L'unica cosa che voglio far notare (a voi la scelta se modificarla o meno) è che quando viene indicata una funzionalità non è molto evidente. Esempio : 
- Scenario principale :
1. Un utente generico accede al sistema;
2. L'utente seleziona la funzionalità visualizza classifica.

La soluzione, se decidete di applicarla, potrebbe essere o mettere semplicemente la prima lettera maiuscola (...Visualizza classifica.) o mettere le virgolette (..."visualizza classifica".)

**Comment by imGretaas** [comment]
thanks!
