### ISSUE TITLE
Documenti Approvati 

### ISSUE THREAD

**Issue by imGretaas** [DreamTeamSWE/Documenti#63]
**Lista dei documenti approvati** | Nome dell'approvatore | Data di approvazione

- [ ] Norme dei Requisiti
- [x] Analisi dei Requisiti
- [ ] Piano di Progetto
- [ ] Piano di Qualifica
- [x] Glossario

Verbali Esterni
- [x] VerbaleEsterno-2021.12.22 | GC | 10.01.22
- [x] VerbaleEsterno-2022.01.26 | MG | 06.02.22
- [x]  VerbaleEsterno-2022.02.08 | EP | 13.02.22 

Verbali Interni
- [x]  VerbaleInterno-2021.11.22 | MB | 22.01.22
- [x] VerbaleInterno-2021.11.29 | LW | 30.11.21
- [x] VerbaleInterno-2021.12.06 | EP | 23.001.22
- [x] VerbaleInterno-2021.12.13 | GC | 08.01.22
- [x] VerbaleInterno-2021.12.20 | GC | 08.01.22
- [x] VerbaleInterno-2021.12.29 | GC | 08.01.22
- [x] VerbaleInterno-2022.01.03 | GC | 09.01.22
- [x] VerbaleInterno-2022.01.07 | MB | 22.01.22
- [x] VerbaleInterno-2022.01.09 | FP | 23.01.22
- [x] VerbaleInterno-2022.01.13 | MB | 22.01.22
- [x] VerbaleInterno-2022.01.20 | MB | 22.01.22
- [x] VerbaleInterno-2022.01.27 | MG | 06.02.22
- [x] VerbaleInterno-2022.02.03 | MG | 06.02.22

 _- Aggiornato in data 11.02.22_

**Comment by francescoo22** [comment]
fatto
