### ISSUE TITLE
Norme di Progetto - verifica di sezione 3.4 , 3.5 (Verifica e validazione) 

### ISSUE THREAD

**Issue by mikigatto93** [DreamTeamSWE/Documenti#72]
- [x] Ricorda mi metterti come verificatore sul registro

**Comment by imGretaas** [comment]
In “Verifica del codice” (3.4.4) c’è un “vedi TODO”.. Se non è da togliere, puoi cambiare label e mettere questa parte da approvare!
per il resto perfetto
