### ISSUE TITLE
Norme di Progetto - verifica di sezione 2.3 , 2.4 (Progettazione e codifica)

### ISSUE THREAD

**Issue by mikigatto93** [DreamTeamSWE/Documenti#73]
- [x] Ricorda mi metterti come verificatore sul registro

**Comment by imGretaas** [comment]
2.4.1 nello scopo della codifica.. “Si può vedere come la trasformazione in codice dell’architettura definita dai Progettisti.” questa frase non è completa..

**Comment by imGretaas** [comment]
per il resto, tutto perfetto!
