### ISSUE TITLE
Piano di Qualifica

### ISSUE THREAD

**Issue by imGretaas** [DreamTeamSWE/Documenti#80]
Cose da fare:

- [x] Grafici di Gulpease
- [x] SPICE

- [x] Da verificare - Michele
- [x] Da approvare - Pietro

**Comment by Pitora** [comment]
Premetto che ho controllato quella che credo non essere la versione finale data la presenza di TODO.
Da sistemare : 
- [x] 2.2.2 -> test di sistema -> TSR2FE12  -> "già"
- [x] D.0.1-> "TS R1FW1" staccato
- [x] F.1.1 ->Rimasto un TODO
- [x] F.2.1 -> Rimasto un TODO

**Comment by Pitora** [comment]
Da sistemare : 
- [x] D -> "TS R1FW1" staccato
- [x] D.0.1 -> "TS R1FW1" staccato
Per il resto, mi sembra tutto giusto. Occhio al registro delle modifiche.

**Comment by francescoo22** [comment]
fatto
