### ISSUE TITLE
Norme di Progetto

### ISSUE THREAD

**Issue by imGretaas** [DreamTeamSWE/Documenti#81]
Cose da fare

- [ ] Da approvare - Edoardo

**Comment by edoardop13** [comment]
controllare la parola "tecnology", più di una volta l'ho vista senza H
- [x] 2.2.3.3 manca uno spazio dopo "analisi dei requisiti"
- [x] 2.2.3.4 nell'elenco puntato, su attori c'è uno spazio prima di ":", anche su "scenario secondario"
- [x] 2.2.3.4 nelle estensioni, correggere "nei"
- [x] 2.2.3.6 su tipologia c'è "(xxx)"
- [x] 2.2.3.6 su fonti mancano i ";" alla fine dell'elenco, e nell'ultima voce ci va il punto, anche in 2.2.3.7
- [x] 2.3.3 c'è una g di troppo all'inizio, anche in 2.3.4
- [x]  2.3.5 nella prima frase va tolto o "sono" o "avere"
- [x] 2.4.3.4 occhio all'accento sulla e
- [x] 3.1.7.2 nel secondo elenco puntato alla prima voce c'è la virgola al posto del ";"
- [x] 3.1.7.4 nell'ultima voce non c'è il punto
- [x] 3.1.7.5 nell'ultima voce non c'è il punto
- [x] 3.1.8.5 manca il punto nell'elenco puntato
- [x] 3.1.9 correggere "verranno applicate la seguente"
- [ ] 3.1.9 gulpease non va nel glossario?
- [x] 3.1.10 su gantproject c'è uno spazio prima dei due punti
- [x] 3.3.3 "della qualità" o "di qualità"?
- [x] 3.4.3.2 correggere la parola "rispetto" e "utilizzata"
- [x] 3.5.2 aggiungere uno spazio dopo "responsabile"
- [x] 4.1.3.2 "od" non mi piace molto, ma è da vedere
- [x] 4.1.4.1 su amministratore di progetto alla seconda voce dell'elenco puntato c'è uno spazio prima del ";"
- [x] 4.1.4.1 su progettista manca l'italico nell'Analisi dei requisiti
- [x] 4.1.4.2 manca il punto alla fine dell'elenco puntato
- [x] 4.2.2 manca amplify e rekognition
- [x] c5 alla prima voce manca il ";"
- [x] c7 e c8 manca il punto alla fine

@mikigatto93 @Pitora

**Comment by francescoo22** [comment]
fatto

**Comment by francescoo22** [comment]
fatto
