### ISSUE TITLE
Norme di progetto

### ISSUE THREAD

**Issue by Pitora** [DreamTeamSWE/Documenti#91]
[Da seguire](https://www.math.unipd.it/~tullio/IS-1/2021/Progetto/RTB/DreamTeam.pdf)

Secondo la valutazione bisogna : 

- [x] Rivedere la gerarchia dei processi primari (§2);
- [x] Togliere le appendici B e C e includerle dove consigliato.
- [x] (?) Riepilogo verbali spiegato (oppure aggiunta in Pianificazione)

**Comment by imGretaas** [comment]
Ho verificato il documento e mi sembra apposto.. c'è qualche errore quà e là, ma nel complesso tutto bene!

**Comment by imGretaas** [comment]
approvato da Matteo
